- hosts: localhost
  connection: local
  roles:
    - openwisp.openwisp2-imagegenerator
  vars:
    openwisp2fw_image_flavours:
      barebones:
        brcm47xx:
          packages:
            - -openvpn-{{ openwisp2fw_ssl_lib }}
#            - -luci-openwisp-{{ openwisp2fw_ssl_lib }}
#            - -luci-theme-openwisp
#            - -luci-mod-openwisp
#            - -uhttpd
#            - -uhttpd-mod-ubus
            - -wpad-mini
    openwisp2fw_source_dir: /home/openwisp2/openwisp2-firmware-source
    openwisp2fw_generator_dir: /home/openwisp2/openwisp2-firmware-generator
    openwisp2fw_bin_dir: /home/openwisp2/openwisp2-firmware-builds
    openwisp2fw_source_targets:
      - system: brcm47xx
        subtarget: mips74k
        profile: "linksys-wrt160n-v3"
    openwisp2fw_organizations:
      - name: homeNet
        flavours:
          - barebones
        luci_openwisp:
          username: "operator"
          password: "OpenWispTwo"
        openwisp:
          url: "https://test.example.com"
          shared_secret: "qwertyuiopasdfghjkl0987654321"
          unmanaged: "{{ openwisp2fw_default_unmanaged }}"
        root_password: "OpenWispTwo"
